# Generated by Django 4.2.3 on 2023-07-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('milk', 'Milk'), ('curd', 'Curd'), ('milkshake', 'Milkshake'), ('paneer', 'Paneer'), ('sweets', 'Sweets'), ('buttermilk', 'Buttermilk'), ('ghee', 'Ghee'), ('lassi', 'Lassi'), ('icecream', 'Icecream')], max_length=15)),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
