# Generated by Django 4.2.3 on 2023-08-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobileno',
            field=models.IntegerField(max_length=10),
        ),
    ]
